// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxyfjewdrzjscgbinudv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4eWZqZXdkcnpqc2NnYmludWR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3OTE3NzUsImV4cCI6MjA4NTM2Nzc3NX0.BnehhtFzrv0sfNAlKqMqSRI7V-YijLIeRpFj9P5Vajo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});